---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: wordpress
spec:
  tls:
    - hosts:
        - bella-margherita.dphx.eu
        - gentlmens-cut.dphx.eu
        - wordpress.cluster.dphx.eu
        - wpadmin.cluster.dphx.eu
      secretName: wordpress-multisite-tls
  rules:
    - host: bella-margherita.dphx.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
    - host: gentlmens-cut.dphx.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
    - host: wordpress.cluster.dphx.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
