---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-php-config
  namespace: wordpress
  labels:
    app: wordpress
data:
  uploads.ini: |
    ; Custom PHP configuration for increased upload limits
    upload_max_filesize = 500M
    post_max_size = 512M
    max_execution_time = 300
    max_input_time = 300
    memory_limit = 512M
