---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: wordpress
  labels:
    app: mysql
data:
  01-wordpress-multisite.sql: |
    USE wordpress;
    
    -- WordPress multisite network tables
    -- These tables are required for WordPress multisite functionality
    
    -- wp_blogs table - stores information about each site in the network
    CREATE TABLE IF NOT EXISTS wp_blogs (
      blog_id bigint(20) NOT NULL AUTO_INCREMENT,
      site_id bigint(20) NOT NULL DEFAULT '0',
      domain varchar(200) NOT NULL DEFAULT '',
      path varchar(100) NOT NULL DEFAULT '',
      registered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      last_updated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      public tinyint(2) NOT NULL DEFAULT '1',
      archived tinyint(2) NOT NULL DEFAULT '0',
      mature tinyint(2) NOT NULL DEFAULT '0',
      spam tinyint(2) NOT NULL DEFAULT '0',
      deleted tinyint(2) NOT NULL DEFAULT '0',
      lang_id int(11) NOT NULL DEFAULT '0',
      PRIMARY KEY (blog_id),
      KEY domain (domain(50),path(5)),
      KEY lang_id (lang_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
    
    -- wp_site table - stores information about the network
    CREATE TABLE IF NOT EXISTS wp_site (
      id bigint(20) NOT NULL AUTO_INCREMENT,
      domain varchar(200) NOT NULL DEFAULT '',
      path varchar(100) NOT NULL DEFAULT '',
      PRIMARY KEY (id),
      KEY domain (domain(140),path(51))
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
    
    -- wp_sitemeta table - stores network-wide meta information
    CREATE TABLE IF NOT EXISTS wp_sitemeta (
      meta_id bigint(20) NOT NULL AUTO_INCREMENT,
      site_id bigint(20) NOT NULL DEFAULT '0',
      meta_key varchar(255) DEFAULT NULL,
      meta_value longtext,
      PRIMARY KEY (meta_id),
      KEY meta_key (meta_key(191)),
      KEY site_id (site_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
    
    -- Insert default network site if not exists
    INSERT IGNORE INTO wp_site (id, domain, path) VALUES (1, 'wordpress.cluster.dphx.eu', '/');
    
    -- Insert main blog/site if not exists
    INSERT IGNORE INTO wp_blogs (blog_id, site_id, domain, path, registered, last_updated, public, archived, mature, spam, deleted, lang_id) 
    VALUES (1, 1, 'wordpress.cluster.dphx.eu', '/', NOW(), NOW(), 1, 0, 0, 0, 0, 0);
    
    -- Insert additional sites for the multisite network domains
    INSERT IGNORE INTO wp_blogs (blog_id, site_id, domain, path, registered, last_updated, public, archived, mature, spam, deleted, lang_id) 
    VALUES 
    (2, 1, 'bella-margherita.dphx.eu', '/', NOW(), NOW(), 1, 0, 0, 0, 0, 0),
    (3, 1, 'gentlmens-cut.dphx.eu', '/', NOW(), NOW(), 1, 0, 0, 0, 0, 0),
    (4, 1, '10.42.0.152', '/', NOW(), NOW(), 1, 0, 0, 0, 0, 0);
    
    -- Insert basic sitemeta for the network
    INSERT IGNORE INTO wp_sitemeta (site_id, meta_key, meta_value) VALUES 
    (1, 'site_name', 'WordPress Multisite Network'),
    (1, 'admin_email', 'admin@wordpress.cluster.dphx.eu'),
    (1, 'admin_user_id', '1'),
    (1, 'registration', 'none'),
    (1, 'upload_filetypes', 'jpg jpeg png gif mp3 mov avi wmv midi mid pdf'),
    (1, 'blog_upload_space', '100'),
    (1, 'fileupload_maxk', '1500'),
    (1, 'site_admins', 'a:1:{i:0;s:5:"admin";}'),
    (1, 'allowedthemes', 'a:0:{}'),
    (1, 'illegal_names', 'a:9:{i:0;s:3:"www";i:1;s:3:"web";i:2;s:4:"root";i:3;s:5:"admin";i:4;s:4:"main";i:5;s:6:"invite";i:6;s:13:"administrator";i:7;s:5:"files";i:8;s:4:"blog";}'),
    (1, 'wpmu_upgrade_site', '49752'),
    (1, 'welcome_email', 'Howdy USERNAME,\n\nYour new SITE_NAME site has been successfully set up at:\nBLOG_URL\n\nYou can log in to the administrator account with the following information:\n\nUsername: USERNAME\nPassword: PASSWORD\nLog in here: BLOG_URLwp-login.php\n\nWe hope you enjoy your new site. Thanks!\n\n--The Team @ SITE_NAME'),
    (1, 'first_post', 'Welcome to %s. This is your first post. Edit or delete it, then start blogging!'),
    (1, 'siteurl', 'https://wordpress.cluster.dphx.eu'),
    (1, 'add_new_users', '0'),
    (1, 'upload_space_check_disabled', '1'),
    (1, 'subdomain_install', '1'),
    (1, 'ms_files_rewriting', '0'),
    (1, 'initial_db_version', '49752'),
    (1, 'active_sitewide_plugins', 'a:0:{}'),
    (1, 'WPLANG', '');